import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Disclaimer | ALLBgremove Liability Information",
    description: "Read the ALLBgremove Disclaimer. Understand the limits of our liability regarding image processing, copyright of uploaded content, and third-party links.",
};

export default function Disclaimer() {
    return (
        <main className="min-h-screen bg-white text-gray-800 flex flex-col items-center py-16 px-6 font-sans">
            <div className="w-full max-w-4xl text-left bg-white rounded-3xl shadow-lg border border-gray-100 p-10 md:p-16">
                <h1 className="text-4xl md:text-5xl font-extrabold mb-8 text-gray-900 border-b border-gray-100 pb-4">Disclaimer</h1>

                <div className="space-y-6 text-lg text-gray-600 leading-relaxed font-medium">
                    <p className="text-sm font-bold text-gray-500 mb-6">Last Updated: October 2023</p>
                    <p>
                        The information provided by ALLBgremove (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) on https://allbgremove.com (the &quot;Site&quot;) is for general informational and utility purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or tool on the Site.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Copyright & Content Liability</h2>
                    <p>
                        UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR RELIANCE ON ANY FEATURE PROVIDED ON THE SITE.
                    </p>
                    <p>
                        Users are solely responsible for the images they upload to ALLBgremove. You must ensure you own the rights to, or have appropriate permission to use, process, and download the edited images. We process images dynamically in memory through Artificial Intelligence and do not store, distribute, or assume copyright liability for any content uploaded by our users.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. External Links Disclaimer</h2>
                    <p>
                        Our Site may contain links to websites or content belonging to or originating from third parties. Such external links, including advertisements served by networks like Google AdSense, are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. Professional Guidance Disclaimer</h2>
                    <p>
                        While our &quot;Passport Photo Maker&quot; and background editing tools aim for high accuracy and standards, they do not constitute official professional legal, immigration, or photography advice. If you are generating a passport photo, you must verify the exact measurements and requirements detailed by your specific government or visa agency before printing or using the photos officially.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. Application Usage</h2>
                    <p>
                        ALLBgremove relies on sophisticated AI models that are computationally intensive. We strive to provide 100% uptime, but the tool is offered &quot;as is.&quot; We are not liable for any downtime, failed processing, buggy outputs, or unexpected artifacts generated by the AI model during background removal operations. We reserve the right to temporarily limit access if server capacity reaches critical overhead limits.
                    </p>

                    <div className="mt-12 text-center text-blue-600 font-semibold text-base hover:underline">
                        <Link href="/">← Go back Home</Link>
                    </div>
                </div>
            </div>
        </main>
    );
}
